name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.x, 2.2.x, devel]
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: |
        nimble install -y --depsOnly
        nimble test
        nimble bench
  docs:
    name: Docs - Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.2.x]
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docs
      run: |
        nimble install -y --depsOnly
        nimble docs
    - name: Deploy docs
      # to view docs on your own fork: push a gh-pages branch on your fork,
      # enable gh-pages in your fork
      # and remove `github.ref == 'refs/heads/master'` below
      if: |
        github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: docs
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
